id: I874BA83B
legacy_id: P009252
ocr_import_info:
  bdrc_scan_id: W22359
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T23:47:54'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T10:15:13.866945+00:00'
last_modified: 2022-08-27 18:15:30.297909
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22359
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22359
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མཚོ་ལྷོའི་གསང་ཆེན་རྙིང་མ་བའི་མཁས་གྲུབ་ཡོངས་ཀྱི་མཛད་རྣམ།
  author: ནོར་བུ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.886817096358485
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I00KG010132:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG010132
      total_pages: 101
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG010132.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.886817096358485
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
