id: I874BA83B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T23:48:12+00:00'
last_modified: '2022-06-08T09:42:04.087633+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22359
  title: མཚོ་ལྷོའི་གསང་ཆེན་རྙིང་མ་བའི་མཁས་གྲུབ་ཡོངས་ཀྱི་མཛད་རྣམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    22EF:
      image_group_id: I00KG010132
      title: ''
      total_pages: 101
      order: 1
      base_file: 22EF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
