id: P009252
initial_creation_type: ocr
source_metadata:
  id: bdr:W22359
  title: མཚོ་ལྷོའི་གསང་ཆེན་རྙིང་མ་བའི་མཁས་གྲུབ་ཡོངས་ཀྱི་མཛད་རྣམ
  author: ''
  volumes:
    48e2336bb63c485390f93847cd8ef7b0:
      image_group_id: I00KG010132
      title: ''
      volume_number: 1
      total_pages: 101
      base_file: v001.txt
